
const mountains=[{id:'bukhansan',name:'북한산 백운대',region:'서울',level:'중급',time:'4시간 30분',hours:4.5,distance:'8.5km',elevation:'950m',rating:'4.8',lat:37.6586,lon:126.9770,desc:'서울에서 접근하기 좋은 대표 암릉 코스입니다. 딕소톤 마운틴 클럽의 메인 이미지와 잘 어울리는 바위 능선 산행을 즐길 수 있습니다.'},{id:'suraksan',name:'수락산',region:'서울',level:'초급',time:'3시간',hours:3,distance:'6.2km',elevation:'638m',rating:'4.7',lat:37.6992,lon:127.0813,desc:'초보자도 도전하기 좋은 서울 북부 산행 코스입니다.'},{id:'seoraksan',name:'설악산 대청봉',region:'강원',level:'고급',time:'6시간',hours:6,distance:'11.4km',elevation:'1,708m',rating:'4.9',lat:38.1194,lon:128.4656,desc:'긴 산행과 큰 고도 차가 있는 고급 코스입니다.'},{id:'jirisan',name:'지리산 천왕봉',region:'경상',level:'고급',time:'7시간',hours:7,distance:'13.8km',elevation:'1,915m',rating:'4.9',lat:35.3369,lon:127.7306,desc:'장거리 산행을 좋아하는 회원에게 추천하는 코스입니다.'},{id:'gwanaksan',name:'관악산 연주대',region:'경기',level:'중급',time:'3시간 30분',hours:3.5,distance:'7.1km',elevation:'629m',rating:'4.6',lat:37.445,lon:126.964,desc:'대중교통 접근성이 좋고 암릉 구간이 재미있는 코스입니다.'}];
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
function toast(msg){let el=$('.toast');if(!el){el=document.createElement('div');el.className='toast';document.body.appendChild(el)}el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function getSaved(){return JSON.parse(localStorage.getItem('dmc.saved')||'[]')}function setSaved(v){localStorage.setItem('dmc.saved',JSON.stringify(v));updateSavedCounts()}function isSaved(id){return getSaved().includes(id)}function toggleSave(id){const s=getSaved();const next=s.includes(id)?s.filter(x=>x!==id):[...s,id];setSaved(next);toast(next.includes(id)?'저장했습니다':'저장을 해제했습니다');renderDynamic()}function updateSavedCounts(){document.querySelectorAll('[data-saved-count]').forEach(el=>el.textContent=getSaved().length)}
function selectedMountain(){const id=new URLSearchParams(location.search).get('mountain')||localStorage.getItem('dmc.lastMountain')||'bukhansan';return mountains.find(m=>m.id===id)||mountains[0]}
function goDashboard(id){localStorage.setItem('dmc.lastMountain',id);location.href='dashboard.html?mountain='+encodeURIComponent(id)}
window.goDashboard=goDashboard;
function renderMountainList(list=mountains){const box=$('[data-mountain-list]');if(!box)return;box.innerHTML=list.length?list.map(m=>`<article class="item"><div class="thumb"></div><div><h3>${m.name}</h3><p class="muted">${m.region} · ${m.level} · ${m.time} · ${m.distance} · ${m.elevation}</p><strong>평점 ${m.rating}</strong></div><button class="btn primary" data-open="${m.id}">보기</button></article>`).join(''):'<div class="empty">조건에 맞는 산이 없습니다.</div>';$$('[data-open]').forEach(b=>b.addEventListener('click',()=>goDashboard(b.dataset.open)))}
function applyFilters(){const q=($('[data-search-input]')?.value||'').trim().toLowerCase();const region=$('.filter-btn.active[data-region]')?.dataset.region||'전체';const level=$('.filter-btn.active[data-level]')?.dataset.level||'전체';let list=mountains.filter(m=>(region==='전체'||m.region===region)&&(level==='전체'||m.level===level)&&(!q||[m.name,m.region,m.level,m.desc].join(' ').toLowerCase().includes(q)));renderMountainList(list)}
function setupArchive(){if(!$('[data-mountain-list]'))return;renderMountainList();$$('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{const group=btn.dataset.region?'data-region':'data-level';$$(`.filter-btn[${group}]`).forEach(b=>b.classList.remove('active'));btn.classList.add('active');applyFilters()}));$('[data-search-input]')?.addEventListener('input',applyFilters)}

function setupClubBanner(){
  const record=$('[data-club-record]');
  const mountain=$('[data-club-mountain]');
  const leader=$('[data-club-leader]');
  if(record) record.addEventListener('click',()=>{location.href='mypage.html#records'});
  if(mountain) mountain.addEventListener('click',()=>goDashboard(mountain.dataset.clubMountain||'gwanaksan'));
  if(leader) leader.addEventListener('click',()=>{location.href='mypage.html#leader'});
}

function setupHomeSearch(){const form=$('[data-home-search]');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const q=$('[data-home-query]').value.trim();location.href='archive.html'+(q?'?q='+encodeURIComponent(q):'')})}
async function renderWeather(m){const box=$('[data-weather]');if(!box)return;box.innerHTML='<p class="muted">실시간 날씨를 불러오는 중입니다.</p>';try{const url=`https://api.open-meteo.com/v1/forecast?latitude=${m.lat}&longitude=${m.lon}&current=temperature_2m,relative_humidity_2m,wind_speed_10m,uv_index,weather_code&timezone=Asia%2FSeoul`;const res=await fetch(url);if(!res.ok)throw new Error('weather');const data=await res.json();const c=data.current;box.innerHTML=`<div class="stats"><div class="stat"><strong>${Math.round(c.temperature_2m)}°C</strong><span class="muted">기온</span></div><div class="stat"><strong>${c.relative_humidity_2m}%</strong><span class="muted">습도</span></div><div class="stat"><strong>${Math.round(c.wind_speed_10m)}km/h</strong><span class="muted">바람</span></div></div><p class="muted">Open-Meteo 무료 API 기준 · UV ${c.uv_index ?? '정보 없음'}</p>`}catch(e){box.innerHTML='<p class="note">날씨 API를 불러오지 못했습니다. GitHub Pages에 올린 뒤 네트워크가 허용되면 자동으로 다시 동작합니다.</p>'}}
function renderDashboard(){if(!$('[data-dashboard]'))return;const m=selectedMountain();document.title=m.name+' | 딕소톤 마운틴 클럽';$('[data-m-title]').textContent=m.name;$('[data-m-desc]').textContent=m.desc;$('[data-m-spec]').innerHTML=`<li>지역: ${m.region}</li><li>난이도: ${m.level}</li><li>예상 소요 시간: ${m.time}</li><li>왕복 거리: ${m.distance}</li><li>누적 고도: ${m.elevation}</li>`;$('[data-map]').src=`https://www.openstreetmap.org/export/embed.html?bbox=${m.lon-0.04}%2C${m.lat-0.03}%2C${m.lon+0.04}%2C${m.lat+0.03}&layer=mapnik&marker=${m.lat}%2C${m.lon}`;$('[data-save]').textContent=isSaved(m.id)?'저장 해제':'저장하기';$('[data-save]').onclick=()=>toggleSave(m.id);$('[data-gpx]').onclick=()=>downloadGpx(m);renderWeather(m);renderReviews(m.id)}
function downloadGpx(m){const gpx=`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="딕소톤 마운틴 클럽"><wpt lat="${m.lat}" lon="${m.lon}"><name>${m.name}</name></wpt><trk><name>${m.name} sample route</name><trkseg><trkpt lat="${m.lat-0.01}" lon="${m.lon-0.01}"></trkpt><trkpt lat="${m.lat}" lon="${m.lon}"></trkpt><trkpt lat="${m.lat+0.01}" lon="${m.lon+0.01}"></trkpt></trkseg></trk></gpx>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([gpx],{type:'application/gpx+xml'}));a.download=m.id+'.gpx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function reviewKey(id){return 'dmc.reviews.'+id}function getReviews(id){return JSON.parse(localStorage.getItem(reviewKey(id))||'[]')}function setReviews(id,v){localStorage.setItem(reviewKey(id),JSON.stringify(v))}
function renderReviews(id){const list=$('[data-review-list]');if(!list)return;const reviews=getReviews(id);list.innerHTML=reviews.length?reviews.map(r=>`<div class="review"><strong>${r.name}</strong><p class="muted">${r.text}</p></div>`).join(''):'<div class="empty">아직 저장된 후기가 없습니다. 첫 후기를 남겨보세요.</div>';const form=$('[data-review-form]');form.onsubmit=e=>{e.preventDefault();const name=$('[data-review-name]').value.trim()||'익명 회원';const text=$('[data-review-text]').value.trim();if(!text){toast('후기를 입력해주세요');return}setReviews(id,[{name,text,date:new Date().toISOString()},...getReviews(id)]);$('[data-review-text]').value='';toast('후기를 저장했습니다');renderReviews(id)}}
function renderMyPage(){if(!$('[data-my-page]'))return;const saved=getSaved().map(id=>mountains.find(m=>m.id===id)).filter(Boolean);$('[data-saved-list]').innerHTML=saved.length?saved.map(m=>`<li><button class="btn ghost" data-open="${m.id}">${m.name}</button></li>`).join(''):'<li class="muted">저장한 산이 없습니다.</li>';$$('[data-open]').forEach(b=>b.addEventListener('click',()=>goDashboard(b.dataset.open)));let reviewCount=mountains.reduce((n,m)=>n+getReviews(m.id).length,0);$('[data-review-count]').textContent=reviewCount;$('[data-saved-count]').textContent=saved.length}
function renderDynamic(){updateSavedCounts();renderDashboard();renderMyPage()}
document.addEventListener('DOMContentLoaded',()=>{const params=new URLSearchParams(location.search);const q=params.get('q');if(q&&$('[data-search-input]'))$('[data-search-input]').value=q;setupHomeSearch();setupClubBanner();setupArchive();if(q)applyFilters();renderDynamic()});
